In [2]:
#DAY 3 - BRANCHING AND LOOPING STATEMENTS

In [3]:
#Display values from 1 to 20 using for loop
#Looping statement should end with colon
for i  in range(1,21):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [4]:
for i  in range(1,21,2):
    print(i)

1
3
5
7
9
11
13
15
17
19


In [5]:
for i  in range(0,50,5):
    print(i)

0
5
10
15
20
25
30
35
40
45


In [6]:
#while loop to print many times
#declare i 
i=0
while(i<10):
    print("hello welcome")
    i=i+1
    print("thank you")

hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you


In [7]:
#function definition and declaration
#keyword def is used
#function with no argument
def cse():
    print("welcome")
    return 

In [8]:
#function call
cse()

welcome


In [9]:
str="Welcome"

In [10]:
str

'Welcome'

In [11]:
#function with argument
def cse(str):
    print(str)
    return 

In [12]:
cse()
#for argument function pass argument

TypeError: cse() missing 1 required positional argument: 'str'

In [13]:
cse(str)

Welcome


In [14]:
a=10

In [15]:
#print string 'a' number of times
def cse(str,a):
    print(str*a)
    return 

In [16]:
cse(str,a)

WelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcome


In [17]:
#NUMPY PACKAGE - Numerical Python
#including numpy package, use import statement
import numpy as np
#np is a user defined variable

In [18]:
#for creating an array in py
#int a[10] - 1D, a[10][10] - 2D, a[10][10][10] -multiD
a=np.array([1,2,3,4,5,6])

In [19]:
a

array([1, 2, 3, 4, 5, 6])

In [20]:
#ndim - to verify the dimension of array
a.ndim

1

In [21]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [22]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
b1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
b1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
b1.ndim

2

In [26]:
#create array using range function
c=np.arange(10,30)

In [27]:
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [28]:
#use step value also
d=np.arange(10,30,2)

In [29]:
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [30]:
#make 1D to 2D
d.shape=(2,5)

In [31]:
d

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [32]:
#printing random array using empty function
x=np.empty([3,2],dtype=int)

In [33]:
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [34]:
#zeros array with zeros fn
x=np.zeros(10)

In [35]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
#print one with ones fn
x=np.ones(10)

In [37]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
#2D array of 12 elements
t=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [39]:
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
str

'Welcome'

In [41]:
#array slicing
t[0]

array([1, 2, 3])

In [42]:
t[1]

array([4, 5, 6])

In [43]:
t[1:3] #or t[1][3]

array([[4, 5, 6],
       [7, 8, 9]])

In [44]:
t[2,2] #t[2][2]

9

In [45]:
t[3,1] #t[3][1]

11

In [46]:
t[3,0:] #t[3][0:]

array([10, 11, 12])

In [47]:
#print the first column alone
#represent column data...use colon comma
t[:,0]

array([ 1,  4,  7, 10])

In [48]:
t[:,2]

array([ 3,  6,  9, 12])

In [49]:
t[:,1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [50]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
m[1:3][0:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
#DAY 4 - 02/02/2023

In [54]:
#copy one array to another array
#print transpose of the matrix
m.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [55]:
#for transpose if we print col and row....only the original value will be printed. Not the transpose form
m[1]

array([5, 6, 7, 8])

In [56]:
m[:,1]

array([ 2,  6, 10, 14])

In [57]:
#copying one array to another
n=m

In [58]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
#add two matrices
m+n

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [60]:
#adding arrays by numpy
np.add(m,n)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [62]:
#subtraction of two matrices
np.subtract(m,n)          #a-b is also valid

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
#multiply two matrices
np.multiply(m,n)       #a*b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [64]:
#division of matrices
np.divide(m,n)          #a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
#square root function
np.sqrt(m)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])